name: Test Native Mode

on: [push]

jobs:
  run_script:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.9", "3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nicegui

      - name: Setup Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update 
          sudo apt-get install -y python3-pyqt5 python3-pyqt5.qtwebengine python3-pyqt5.qtwebchannel libqt5webkit5-dev
          sudo apt-get install -y libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0 python3-gi python3-gi-cairo gir1.2-webkit2-4.0
          sudo apt-get install -y xvfb
          pip install pygobject qtpy pyside2
          Xvfb :99 -screen 0 1024x768x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run Script (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          python test_native_mode.py &
          sleep 100
          cat output.log
        shell: bash

      - name: Run Script (Windows)
        if: runner.os == 'Windows'
        run: |
          Start-Process -FilePath "python" -ArgumentList "test_native_mode.py" -NoNewWindow
          Start-Sleep -Seconds 100
          Get-Content output.log
        shell: pwsh

      - name: Check Roundtrip
        run: grep -q "Roundtrip works!" output.log
