name: Test Native Mode

on: [push]

jobs:
  run_script:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.9", "3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install browser (Windows) # it's preinstalled on macos and linux
        if: runner.os == 'Windows'
        run: |
          choco install firefox

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nicegui

      - name: Install Xvfb (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install Xvfb (macOS)
        if: runner.os == 'macOS'
        run: brew install xvfb

      - name: Setup Xvfb
        if: runner.os == 'macOS' || runner.os == 'Linux'
        run: |
          export DISPLAY=:99
          Xvfb :99 &

      - name: Run Script
        id: run_script
        run: |
          python test_native_mode.py &  # this creates the "result" file after browser connects
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            TIMEOUT 10
          else
            sleep 10
          fi

      - name: Check output
        run: grep -q "Roundtrip works!" result

      - name: Clean up
        run: |
          pkill -f test_native_mode.py
          rm output.log
