name: Run Tests

on: [push]

jobs:
  test:
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.2.2"
      - name: install dependencies
        run: |
          poetry install
          # try fix issue with importlib_resources
          pip install importlib-resources
      - name: test startup
        run: poetry run ./test_startup.sh
      - name: setup chromedriver
        uses: nanasess/setup-chromedriver@v1
      - name: pytest
        run: poetry run pytest

  slack:
    needs:
      - test
    if: always() # also execute when test fails
    runs-on: ubuntu-latest
    steps:
      - name: Determine if we need to notify
        uses: Jimdo/should-i-notify-action@main
        id: should_notify
        with:
          needs_context: ${{ toJson(needs) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack workflow notification
        if: steps.should_notify.outputs.should_send_message == 'yes'
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_ROBOTICS_CI_WEBHOOK }}
          channel: "robotik-ci"
          name: "NiceGUI"
